import * as Components from './components'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    VeuiAccordion: Components.Accordion
    VeuiAlertBox: Components.AlertBox
    VeuiAnchor: Components.Anchor
    VeuiAutocomplete: Components.Autocomplete
    VeuiBadge: Components.Badge
    VeuiBreadcrumb: Components.Breadcrumb
    VeuiBreadcrumbItem: Components.BreadcrumbItem
    VeuiButton: Components.Button
    VeuiButtonGroup: Components.ButtonGroup
    VeuiCalendar: Components.Calendar
    VeuiCarousel: Components.Carousel
    VeuiCascader: Components.Cascader
    VeuiCheckButtonGroup: Components.CheckButtonGroup
    VeuiCheckbox: Components.Checkbox
    VeuiCheckboxGroup: Components.CheckboxGroup
    VeuiCollapse: Components.Collapse
    VeuiColumn: Components.Column
    VeuiConfigProvider: Components.ConfigProvider
    VeuiConfirmBox: Components.ConfirmBox
    VeuiDatePicker: Components.DatePicker
    VeuiDialog: Components.Dialog
    VeuiDrawer: Components.Drawer
    VeuiDropdown: Components.Dropdown
    VeuiFilterPanel: Components.FilterPanel
    VeuiField: Components.Field
    VeuiFieldset: Components.Fieldset
    VeuiForm: Components.Form
    VeuiGridColumn: Components.GridColumn
    VeuiGridContainer: Components.GridContainer
    VeuiGridRow: Components.GridRow
    VeuiIcon: Components.Icon
    VeuiInput: Components.Input
    VeuiInputGroup: Components.InputGroup
    VeuiLabel: Components.Label
    VeuiLightbox: Components.Lightbox
    VeuiLink: Components.Link
    VeuiLoading: Components.Loading
    VeuiMenu: Components.Menu
    VeuiMessage: Components.Message
    VeuiNav: Components.Nav
    VeuiNumberInput: Components.NumberInput
    VeuiOption: Components.Option
    VeuiOptionGroup: Components.OptionGroup
    VeuiOverlay: Components.Overlay
    VeuiPagination: Components.Pagination
    VeuiPopover: Components.Popover
    VeuiProgress: Components.Progress
    VeuiPromptBox: Components.PromptBox
    VeuiRadio: Components.Radio
    VeuiRadioButtonGroup: Components.RadioButtonGroup
    VeuiRadioGroup: Components.RadioGroup
    VeuiSearchBox: Components.SearchBox
    VeuiSelect: Components.Select
    VeuiSlider: Components.Slider
    VeuiSpan: Components.Span
    VeuiSteps: Components.Steps
    VeuiSwitch: Components.Switch
    VeuiTab: Components.Tab
    VeuiTable: Components.Table
    VeuiTabs: Components.Tabs
    VeuiTag: Components.Tag
    VeuiTextarea: Components.Textarea
    VeuiTimePicker: Components.TimePicker
    VeuiToast: Components.Toast
    VeuiToastList: Components.ToastList
    VeuiTooltip: Components.Tooltip
    VeuiTransfer: Components.Transfer
    VeuiTree: Components.Tree
    VeuiUploader: Components.Uploader
    VeuiContent: Components.Content
    VeuiFooter: Components.Footer
    VeuiHeader: Components.Header
    VeuiLayout: Components.Layout
    VeuiSidebar: Components.Sidebar
    VeuiSidenav: Components.Sidenav
    VeuiEmpty: Components.Empty
  }
}
