import { VeuiDefineComponent } from './common/context'
import Accordion from './components/accordion'
import Alert from './components/alert'
import AlertBox from './components/alert-box'
import Anchor from './components/anchor'
import Autocomplete from './components/autocomplete'
import Badge from './components/badge'
import Breadcrumb from './components/breadcrumb'
import BreadcrumbItem from './components/breadcrumb-item'
import Button from './components/button'
import ButtonGroup from './components/button-group'
import Calendar from './components/calendar'
import Carousel from './components/carousel'
import Cascader from './components/cascader'
import CheckButtonGroup from './components/check-button-group'
import Checkbox from './components/checkbox'
import CheckboxGroup from './components/checkbox-group'
import Collapse from './components/collapse'
import Column from './components/column'
import ConfigProvider from './components/config-provider'
import ConfirmBox from './components/confirm-box'
import DatePicker from './components/date-picker'
import Dialog from './components/dialog'
import Drawer from './components/drawer'
import Dropdown from './components/dropdown'
import FilterPanel from './components/filter-panel'
import Field from './components/field'
import Fieldset from './components/fieldset'
import Form from './components/form'
import GridColumn from './components/grid-column'
import GridContainer from './components/grid-container'
import GridRow from './components/grid-row'
import Icon from './components/icon'
import Input from './components/input'
import InputGroup from './components/input-group'
import Label from './components/label'
import Lightbox from './components/lightbox'
import Link from './components/link'
import Loading from './components/loading'
import Menu from './components/menu'
import Nav from './components/nav'
import NumberInput from './components/number-input'
import Option from './components/option'
import OptionGroup from './components/option-group'
import Overlay from './components/overlay'
import Pagination from './components/pagination'
import Popover from './components/popover'
import Progress from './components/progress'
import PromptBox from './components/prompt-box'
import Radio from './components/radio'
import RadioButtonGroup from './components/radio-button-group'
import RadioGroup from './components/radio-group'
import SearchBox from './components/search-box'
import Select from './components/select'
import Slider from './components/slider'
import Span from './components/span'
import Steps from './components/steps'
import Switch from './components/switch'
import Tab from './components/tab'
import Table from './components/table'
import Tabs from './components/tabs'
import Tag from './components/tag'
import Textarea from './components/textarea'
import TimePicker from './components/time-picker'
import Toast from './components/toast'
import ToastList from './components/toast-list'
import Tooltip from './components/tooltip'
import Transfer from './components/transfer'
import Tree from './components/tree'
import Uploader from './components/uploader'

export const Accordion: VeuiDefineComponent<Accordion>
export const Alert: VeuiDefineComponent<Alert>
export const AlertBox: VeuiDefineComponent<AlertBox>
export const Anchor: VeuiDefineComponent<Anchor>
export const Autocomplete: VeuiDefineComponent<Autocomplete>
export const Badge: VeuiDefineComponent<Badge>
export const Breadcrumb: VeuiDefineComponent<Breadcrumb>
export const BreadcrumbItem: VeuiDefineComponent<BreadcrumbItem>
export const Button: VeuiDefineComponent<Button>
export const ButtonGroup: VeuiDefineComponent<ButtonGroup>
export const Calendar: VeuiDefineComponent<Calendar>
export const Carousel: VeuiDefineComponent<Carousel>
export const Cascader: VeuiDefineComponent<Cascader>
export const CheckButtonGroup: VeuiDefineComponent<CheckButtonGroup>
export const Checkbox: VeuiDefineComponent<Checkbox>
export const CheckboxGroup: VeuiDefineComponent<CheckboxGroup>
export const Collapse: VeuiDefineComponent<Collapse>
export const Column: VeuiDefineComponent<Column>
export const ConfigProvider: VeuiDefineComponent<ConfigProvider>
export const ConfirmBox: VeuiDefineComponent<ConfirmBox>
export const DatePicker: VeuiDefineComponent<DatePicker>
export const Dialog: VeuiDefineComponent<Dialog>
export const Drawer: VeuiDefineComponent<Drawer>
export const Dropdown: VeuiDefineComponent<Dropdown>
export const Field: VeuiDefineComponent<Field>
export const Fieldset: VeuiDefineComponent<Fieldset>
export const FilterPanel: VeuiDefineComponent<FilterPanel>
export const Form: VeuiDefineComponent<Form>
export const GridColumn: VeuiDefineComponent<GridColumn>
export const GridContainer: VeuiDefineComponent<GridContainer>
export const GridRow: VeuiDefineComponent<GridRow>
export const Icon: VeuiDefineComponent<Icon>
export const Input: VeuiDefineComponent<Input>
export const InputGroup: VeuiDefineComponent<InputGroup>
export const Label: VeuiDefineComponent<Label>
export const Lightbox: VeuiDefineComponent<Lightbox>
export const Link: VeuiDefineComponent<Link>
export const Loading: VeuiDefineComponent<Loading>
export const Menu: VeuiDefineComponent<Menu>
export const Nav: VeuiDefineComponent<Nav>
export const NumberInput: VeuiDefineComponent<NumberInput>
export const Option: VeuiDefineComponent<Option>
export const OptionGroup: VeuiDefineComponent<OptionGroup>
export const Overlay: VeuiDefineComponent<Overlay>
export const Pagination: VeuiDefineComponent<Pagination>
export const Popover: VeuiDefineComponent<Popover>
export const Progress: VeuiDefineComponent<Progress>
export const PromptBox: VeuiDefineComponent<PromptBox>
export const Radio: VeuiDefineComponent<Radio>
export const RadioButtonGroup: VeuiDefineComponent<RadioButtonGroup>
export const RadioGroup: VeuiDefineComponent<RadioGroup>
export const SearchBox: VeuiDefineComponent<SearchBox>
export const Select: VeuiDefineComponent<Select>
export const Slider: VeuiDefineComponent<Slider>
export const Span: VeuiDefineComponent<Span>
export const Steps: VeuiDefineComponent<Steps>
export const Switch: VeuiDefineComponent<Switch>
export const Tab: VeuiDefineComponent<Tab>
export const Table: VeuiDefineComponent<Table>
export const Tabs: VeuiDefineComponent<Tabs>
export const Tag: VeuiDefineComponent<Tag>
export const Textarea: VeuiDefineComponent<Textarea>
export const TimePicker: VeuiDefineComponent<TimePicker>
export const Toast: VeuiDefineComponent<Toast>
export const ToastList: VeuiDefineComponent<ToastList>
export const Tooltip: VeuiDefineComponent<Tooltip>
export const Transfer: VeuiDefineComponent<Transfer>
export const Tree: VeuiDefineComponent<Tree>
export const Uploader: VeuiDefineComponent<Uploader>
